/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Application.Controller.Simulation;
import Application.Controller.Time;
import Domain.Trips.Segment;
import Domain.Trips.Trip;
import Domain.Vehicule.Vehicule;
import Domain.Vehicule.VehiculePosition;
import javax.swing.JOptionPane;

/**
 *
 * @author Élise
 */
public class ModifyVehicule extends javax.swing.JFrame {

    private Simulation controller;
    private Vehicule vehicule = null;
    /**
     * Creates new form ModifyVehicule
     */
    public ModifyVehicule(Simulation _controller) 
    {
        controller = _controller;
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }
    
    public ModifyVehicule(Simulation _controller, Vehicule _vehicule) 
    {
        controller = _controller;
        vehicule = _vehicule;
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTrip = new javax.swing.JLabel();
        cmbTrip = new javax.swing.JComboBox();
        lblOriginStop = new javax.swing.JLabel();
        cmbOriginStop = new javax.swing.JComboBox();
        btnOk = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Ajouter, modifier ou supprimer un véhicule");

        lblName.setText("Nom :");

        lblTrip.setText("Trajet: ");

        cmbTrip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblOriginStop.setText("Arrêt de départ: ");

        cmbOriginStop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));


        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        
        this.cmbTrip.removeAllItems();
        this.cmbOriginStop.removeAllItems();
        
        if(vehicule == null)
        {
            for(int i = 0; i < controller.getListTrip().size(); i++)
            {
                this.cmbTrip.addItem(controller.getListTrip().get(i).getName());
            }       

            for(int i = 0; i < controller.getListTrip().size(); i++)
            {
                if (cmbTrip.getSelectedItem().toString().equalsIgnoreCase(controller.getListTrip().get(i).getName()))
                {
                    for (int j = 0; j < controller.getListTrip().get(i).getAllSegments().size(); j++)
                    {
                        this.cmbOriginStop.addItem(controller.getListTrip().get(i).getAllSegments().get(j).getOriginNode().getName());
                    }
                }
            }
        }else{
            this.txtName.setText(vehicule.getName());
            for(int i = 0; i < controller.getListTrip().size(); i++)
            {
                this.cmbTrip.addItem(controller.getListTrip().get(i).getName());
            }
            this.cmbTrip.setSelectedItem(vehicule.getTrip().getName());       

            for(int i = 0; i < controller.getListTrip().size(); i++)
            {
                if (cmbTrip.getSelectedItem().toString().equalsIgnoreCase(controller.getListTrip().get(i).getName()))
                {
                    for (int j = 0; j < controller.getListTrip().get(i).getAllSegments().size(); j++)
                    {
                        this.cmbOriginStop.addItem(controller.getListTrip().get(i).getAllSegments().get(j).getOriginNode().getName());
                    }
                }
            }            
            this.cmbOriginStop.setSelectedItem(vehicule.getCurrentPosition().getCurrentSegment().getOriginNode().getName());
        }
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOriginStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbOriginStop, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblTrip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnOk)
                        .addGap(29, 29, 29)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrip)
                    .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOriginStop)
                    .addComponent(cmbOriginStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnDelete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
	}
	
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if(!(txtName.getText().isEmpty()))
        {
            if (vehicule == null)
            {
                String selectedTripName = cmbTrip.getSelectedItem().toString();
                Trip trip = null;
                for(int i=0; i < controller.getListTrip().size(); i++)
                {
                    if(controller.getListTrip().get(i).getName().equalsIgnoreCase(selectedTripName))
                    {
                        trip = controller.getListTrip().get(i);
                        break;
                    }
                }
                if(trip != null)
                {
                    String selectedNodeName = cmbOriginStop.getSelectedItem().toString();
                    Segment spawnSegment = null;
                    for(int i=0; i < trip.getAllSegments().size(); i++)
                    {
                        if(trip.getAllSegments().get(i).getOriginNode().getName().equalsIgnoreCase(selectedNodeName))
                        {
                            spawnSegment = trip.getAllSegments().get(i);
                            break;
                        }
                    }
                    

                    controller.addVehicule(trip ,spawnSegment, txtName.getText());
                }
            }
            else
            {
                Trip trip = null;
                for (int i = 0; i < controller.getListTrip().size(); i++)
                {
                    if (controller.getListTrip().get(i).getName().equalsIgnoreCase(cmbTrip.getSelectedItem().toString()))
                    {
                        trip = controller.getListTrip().get(i);
                    }
                }
                if(trip != null)
                {
                    String selectedNodeName = cmbOriginStop.getSelectedItem().toString();
                    Segment spawnSegment = null;
                    for(int i=0; i < trip.getAllSegments().size(); i++)
                    {
                        if(trip.getAllSegments().get(i).getOriginNode().getName().equalsIgnoreCase(selectedNodeName))
                        {
                            spawnSegment = trip.getAllSegments().get(i);
                            break;
                        }
                    }
                    vehicule.setName(txtName.getText());
                    vehicule.setTrip(trip);
                    vehicule.setCurrentPosition(new VehiculePosition(spawnSegment, this.controller.getCurrentTime()));
                }else{
                    JOptionPane.showMessageDialog(this, "Une erreur est survenu, désolé de l'inconvénient.");
                }
            }
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Assurez-vous d'avoir rempli tous les champs avant \nla création ou la modification du générateur de véhicule.");
        }
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) 
    {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Êtes-vous certain de vouloir supprimer ce véhicule ?","Avertissement",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            controller.deleteVehicule(vehicule);
            dispose();
        }
    }
    
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbOriginStop;
    private javax.swing.JComboBox cmbTrip;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOriginStop;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrip;
    private javax.swing.JTextField txtName;
}
