/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Application.Controller.Simulation;
import javax.swing.JOptionPane;
import javax.swing.ComboBoxModel;
/**
 *
 * @author Élise
 */
public class ModifyItinary extends javax.swing.JFrame 
{

    private Simulation controller;
    private Domain.Client.Itinary itinary;
    /**
     * Creates new form ModifyItinary
     */
    public ModifyItinary(Simulation _controller, Domain.Client.Itinary _itinary) 
    {
        this.controller = _controller;
        this.itinary = _itinary;
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    public Domain.Client.Itinary getItinary()
    {
        return this.itinary;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTrip = new javax.swing.JLabel();
        lblOriginStop = new javax.swing.JLabel();
        lblDestiStop = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbTrip = new javax.swing.JComboBox();
        cmbOriginStop = new javax.swing.JComboBox();
        cmbDestStop = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Ajouter, modifier ou supprimer un itinéraire");

        lblTrip.setText("Trajet: ");

        lblOriginStop.setText("Arrêt d'origine: ");

        lblDestiStop.setText("Arrêt de destination:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnDelete.setText("Supprimer");        
        
        cmbTrip.addActionListener (new java.awt.event.ActionListener () 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                cmbOriginStop.removeAll();
                cmbDestStop.removeAll();
                for(int i = 0; i < controller.getListOriginNodeByTrip(controller.getTripByName(cmbTrip.getSelectedItem().toString())).size(); i++)
                {
                    cmbOriginStop.addItem(controller.getListOriginNodeByTrip(controller.getTripByName(cmbTrip.getSelectedItem().toString())).get(i).getName());
                }
                for(int i = 0; i < controller.getListDestinationNodeByTrip(controller.getTripByName(cmbTrip.getSelectedItem().toString())).size(); i++)
                {
                    cmbDestStop.addItem(controller.getListDestinationNodeByTrip(controller.getTripByName(cmbTrip.getSelectedItem().toString())).get(i).getName());
                }
            }
        });
        
        for(int i = 0; i < controller.getListTrip().size(); i++)
        {
            cmbTrip.addItem(controller.getListTrip().get(i).getName());
        }
        
        /*cmbTrip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbOriginStop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDestStop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDestiStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDestStop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOriginStop)
                                    .addComponent(lblTrip))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbOriginStop, 0, 128, Short.MAX_VALUE)
                                    .addComponent(cmbTrip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnOk)
                        .addGap(54, 54, 54)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrip)
                    .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOriginStop)
                    .addComponent(cmbOriginStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestiStop)
                    .addComponent(cmbDestStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnDelete))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }
    
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) 
    {
        if(!(cmbTrip.getItemCount() == 0 || cmbOriginStop.getItemCount() == 0 || cmbDestStop.getItemCount() == 0))
        {
            if (itinary != null)
            {
                itinary.setTrip(controller.getTripByName(cmbTrip.getSelectedItem().toString()));
                itinary.setOriginStop((Domain.Node.Stop)controller.getNodeByName(cmbOriginStop.getSelectedItem().toString()));
                itinary.setDestinationStop((Domain.Node.Stop)controller.getNodeByName(cmbDestStop.getSelectedItem().toString()));
            }
            else
            {
                Domain.Node.Stop stop = (Domain.Node.Stop)controller.getNodeByName(cmbOriginStop.getSelectedItem().toString());
                itinary = new Domain.Client.Itinary((Domain.Node.Stop)controller.getNodeByName(cmbOriginStop.getSelectedItem().toString()), 
                                                    (Domain.Node.Stop)controller.getNodeByName(cmbDestStop.getSelectedItem().toString()), 
                                                    controller.getTripByName(cmbTrip.getSelectedItem().toString()));
            }
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Assurez-vous d'avoir sélectionné des valeurs pour tous les champs");
        }
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) 
    {
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyItinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyItinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyItinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyItinary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ModifyItinary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbDestStop;
    private javax.swing.JComboBox cmbOriginStop;
    private javax.swing.JComboBox cmbTrip;
    private javax.swing.JLabel lblDestiStop;
    private javax.swing.JLabel lblOriginStop;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrip;
    // End of variables declaration//GEN-END:variables
}
